# Generated by Django 4.1.10 on 2023-09-14 09:32

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import service.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(upload_to=service.models.get_attachment_path),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='service.service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_confirmed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
