# Generated by Django 4.1.10 on 2023-09-14 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': 'Attachment', 'verbose_name_plural': 'Attachments'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='servicetype',
            options={'verbose_name': 'Service type', 'verbose_name_plural': 'Service types'},
        ),
    ]
